language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t sathyapr/dockerproject1 -f Dockerfile.dev . 

script:
  - docker run -e CI=true sathyapr/dockerproject1 npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "dockerproject"
  env: "Dockerproject-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-864090089332"
  bucket_path: "dockerproject"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"