language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t sathyapr/dockerproject1 -f Dockerfile.dev . 

script:
  - docker run -e CI=true sathyapr/dockerproject1 npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-ap-southeast-1-864090089332"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY